name: korp-teste

services:
  postgres:
    image: postgres:18.4-alpine
    container_name: korp-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"

    volumes:
      - dados_postgres:/var/lib/postgresql
      - ./infraestrutura/postgres/inicializacao:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  dados_postgres:
