// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicoFaturamento.Api.Dados;

#nullable disable

namespace ServicoFaturamento.Api.Dados.Migracoes
{
    [DbContext(typeof(FaturamentoDbContext))]
    partial class FaturamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServicoFaturamento.Api.Dominio.ItemNotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("NotaFiscalNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("nota_fiscal_numero");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalNumero", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_itens_nota_fiscal_produto");

                    b.ToTable("itens_nota_fiscal", null, t =>
                        {
                            t.HasCheckConstraint("ck_itens_nota_fiscal_quantidade_positiva", "\"quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("ServicoFaturamento.Api.Dominio.NotaFiscal", b =>
                {
                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Numero");

                    b.ToTable("notas_fiscais", null, t =>
                        {
                            t.HasCheckConstraint("ck_notas_fiscais_status", "\"status\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ServicoFaturamento.Api.Dominio.ItemNotaFiscal", b =>
                {
                    b.HasOne("ServicoFaturamento.Api.Dominio.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("ServicoFaturamento.Api.Dominio.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
